### PR TITLE
add clickout url to optional enrichment of /metrics

### PR DESCRIPTION
**Pull request by twessling-icas**

### CODE REVIEW

**Review by homiak — COMMENTED** [review]
would be nice to have actual changes committed separately from generated staff, now I am not sure what actually been changed

**Comment by remenska** [comment]
for sake of consistency: do we really call it `clickout url` in sellside? or `website url` maybe?

**Comment by twessling-icas** [comment]
@homiak check the .RST files for that :) Everything gets generated from those.
@remenska I was doubting about that, I'm afraid that 'website' is an overloaded term here - whether it is the url on the (classifieds) website where the ad can be found or the customer's website where the ad points to... Am I being too paranoid here?

**Comment by remenska** [comment]
@twessling-icas you're right, which is all the more reason to have consistency (imho the product owner should own the terminology and it should be religiously strict and consistent).
What I see from buyside and sellside:

https://pages.github.es.ecg.tools/ecg-icas/api/doc/icas/buyside/responseStructs/resp-struct-adlite.html

http://ecg-icas.github.io/icas/doc/prod/ads.html#ad-links-url

seems like `external URL` is the way we describe this field.

**Review by homiak — DISMISSED** [review]

**Comment by twessling-icas** [comment]
You're right @remenska , I'll change the code & docs to become currentAdExternalURL, does that sound better?

**Review by remenska — APPROVED** [review]

**Pull request merged**
